### ISSUE TITLE
Support for client_credentials (server)

### ISSUE THREAD

**Issue by Place1** [zitadel/oidc#169]
**Is your feature request related to a problem? Please describe.**

The server implementation of /authorize doesn't support the "client_credentials" grant type yet

```json
{
    "error":"unsupported_grant_type",
    "error_description":"client_credentials not supported"
}
```

I'd like to make use of the client_credentials grant so that I can implement a solution that allows applications to request service tokens.

The application client would use the "client_credentials" grant to receive a token with a list of scopes that the client has requested and is allowed to use.

In a multi-service architecture this is very useful because it allows services to request service tokens that they can then use to call other APIs.

**Describe the solution you'd like**

The server library can implement support for the client_credentials grant by:

1. calling storage.AuthorizeClientIDSecret
2. calling storage.GetClientByClientID
3. calling client.IsScopeAllowed for each requested scope

I'm hoping this would be enough for an MVP solution.

**Comment by adlerhurst** [comment]
hi @Place1 

Thanks for your request. 🙏🏻

@livio-a will answer your question as soon as possible

**Comment by Place1** [comment]
Thanks for taking a look! I’d be happy to elaborate on the use case or help
with implementation where possible

**Comment by Place1** [comment]
Here’s a link that describes my use case:
https://auth0.com/blog/using-m2m-authorization/

I’ve basically got a central oidc service that I’d like to use for service
authentication using client_credentials grant as described in the article.

The oidc service issues JWTs so that services can make authenticated api
calls via an api gateway that verifies the token.

Do you have a link about the JWT Profile flow? I’m not sure I’ve understood
what it is. Is it a flow that allows services to get a token?

**Comment by fforootd** [comment]
Got it!

`JWT Profile` is defined in [RFC 7523](https://datatracker.ietf.org/doc/html/rfc7523) and can be used as a more secure alternative to `Client Credentials`. The TL;DR is that with a private public key mechanic you can authenticate a `machine` or `client` against your IAM system to receive an `Access Token`.

So for example when you are working with ZITADEL (our OSS IAM) we recommend using [JWT Profile as Authorization Grant](https://docs.zitadel.ch/docs/apis/openidoauth/grant-types#using-jwts-as-authorization-grants) to allow `machines` (in our case we call them service users) to request tokens from the IAM. 

So depending on the IAM you use the answer might diverge a little. As far as I am aware with Keycloak and Auth0 the treat all machines as `clients` and don't differentiate between them.  [Google ](https://developers.google.com/identity/protocols/oauth2/service-account) and ZITADEL on the other side strictly separate the `clients` and `machines`.
We think separating the `client` from `machines` is important here. Because a  `client` acts on behalf of a `humane user` but the `machine` can act on its own.

Even with that sad, we could opt for allowing `Client Credentials` to be used for `machines` aka. `service users` if the need arises but we would recommend having a look on `JWT Profile` first 😁 

Hope this helps

**Comment by Place1** [comment]
Thanks for the detailed information and links.

So if i'm understanding correctly the flow works like this:

1. the machine has a private key which it uses to generate a JWT assertion (signed jwt)
2. it sents that to the token endpoint with the jwt-bearer grant type
3. caos/oidc implements client assertion validation by checking the assertion is signed with a trusted public key (shared previously)

**Comment by Place1** [comment]
I've posted a PR here: https://github.com/caos/oidc/pull/172
