### ISSUE TITLE
Enhance id_token with custom claims

### ISSUE THREAD

**Issue by michaelholtermann** [zitadel/oidc#246]
**Is your feature request related to a problem? Please describe.**
My login information is provided a legacy system, not compliant to any standard. It's two-phased and reads quite usual:

1. user logs in via username/password, the legacy system returns a secret (some token, but not OIDC compliant)
2. now I can call the legacy system with that secret and reveal things like user name, mail address, roles etc.

I'm able to "wrap" this legacy login into OIDC compliant `id_token` with `zitadel/oidc`, by implementing these to steps within `CheckUsernamePassword(username, password, id string) error` from the example. ✅ 

But later, I need the original token from step 1 to call other APIs from the legacy system. 
In addition, I would like to add other information from the two calls as well, like some user roles that are defined in that legacy system.

What I'm trying to achieve is to transport the original token from the login to my backend system via the `id_token`.

I was already able to append the information the implementation of the `op.AuthRequest` interface.

**Describe the solution you'd like**
Currently, during the login process, `op.CreateIDToken()` is called. 

This calls OPStorage.SetUserinfoFromScopes(). In the example in `example/server/storage/storage.go` this call fills firstname, phone etc..

I would suggest to extend that call so it contains the `op.AuthRequest` from `op.CreateIDToken`. Then I could copy the information from that request to the `id_token`.

This must be done backwards compatible, of course.

Alternatively, a second call function to copy "custom attributes" might be a solution.

**Describe alternatives you've considered**
I could save the original token in some persistent store, so that my backend systems could fetch it from there once its needed, but this would break the "self containment" of the id_token, at least somehow.

**Additional context**
I'd be happy to provide a PR, but maybe there are other ideas or even vetos against such a feature.

**Comment by hifabienne** [comment]
@livio-a Can you have a look at this?

**Comment by livio-a** [comment]
Hey @michaelholtermann 

I'm not totally sure if I got you correct and have some questions:

What do you mean by `some token, but not OIDC compliant`?
Because you write, that you `can call the legacy system with that secret and reveal things like user name, mail address, roles etc.`. This is sound like an access token. Which leads me to the second question: Why do you need to wrap it into the id_token?
IMO the id_token should only be used for identification and not used to access an API / resource server.


Regarding custom claim in id_token. There's already a possibility using scopes (there's also one for JWT access tokens):
https://github.com/zitadel/oidc/blob/b031c1f29786b15a42dbbab74613d6beb29730d9/pkg/op/token.go#L131

E.g. in ZITADEL we use it to configure it roles should be in the token:
https://github.com/zitadel/zitadel/blob/main/internal/api/oidc/client_converter.go#L72

... and we set some scopes depending on the project / client:
https://github.com/zitadel/zitadel/blob/main/internal/api/oidc/auth_request.go#L27

Assertion of the roles into the id_token / userinfo response:
https://github.com/zitadel/zitadel/blob/main/internal/api/oidc/client.go#L290-L296

And special case for PAT (personal acceess token), were we automatically assert some scopes on the introspection,
so that custom claims will be returned
https://github.com/zitadel/zitadel/blob/main/internal/api/oidc/client.go#L186

Hope this already clarifies it a bit. Looking forward to your answer.
I'm sure we'll find a solution for your case.

**Comment by michaelholtermann** [comment]
HI @livio-a.

thanks for the reply. I'm sorry if my request sounds somehow weird. I'm not happy with our current solution, but it's a legacy system I have to live with.

> What do you mean by some token, but not OIDC compliant?
Because you write, that you can call the legacy system with that secret and reveal things like user name, mail address, roles etc.. This is sound like an access token. Which leads me to the second question: Why do you need to wrap it into the id_token?

Technically, it's some base64 encoded JSON that does not contain any useful information for me as the caller. It's behavior is more like an API key, that is, I can call other endpoints with it of that legacy system to reveal something useful. For example, I can query the PII of the original user by calling a certain endpoint with that token, or upload some data to that system with the same token.

But I cannot interpret the contents of this token, or rebuild it later.

I try to isolate that behavior of the legacy system as far as possible. In my own system, I would like to go fully into OAuth2/OIDC. But often I have to call that legacy system later, for which I need it's original token.

I hope this make my idea more clear, but I'm happy to discuss further :-)

Thanks again!

**Comment by hifabienne** [comment]
@livio-a can you have a look at this again?

**Comment by muhlemmer** [comment]
@michaelholtermann  Would the API discussed in #323 help you?

We get similar feedback from other users. Basically, our storage interfaces are an abstraction of what we thought we needed for Zitadel. But, might be too restrictive for other implementations. Therefore we are open to increasing the data passed to the storage interface API.

For example, currently we discard info that is available in the incoming HTTP request, which we know we already have in the database (zitadel), so we prefer to use our own state over the state in the request. However, this solution might not be suitable for others.

After some internal discussions, we came to the agreement that it doesn't harm to pass a bigger data object to the storage layer, like an AuthRequest, TokenRequest or more. For Zitadel that would mean we just extract the needed data from there.

Please note that we open to this kind of changes, but they are not on our list of priorities. As this is also an open source project, we are open to contributions through PR. For changes to the package API, I would suggest to make a complete proposal in an issue first.

> This must be done backwards compatible, of course.

Breaking changes are allowed and should target the `next` branch. Currently we are working towards a `v3` release.

**Comment by hifabienne** [comment]
As we didn't hear back and the api that @muhlemmer mentioned above has been merged I will close this issue.
Feel free to reopen if its not solved, or more information can be provided
