### ISSUE TITLE
Wildcard URIs are not valid redirect URIs

### ISSUE THREAD

**Issue by mitchwadair** [zitadel/oidc#293]
**Describe the bug**
Wildcard URIs, like `*` or `https://example.com/*` are not recognized as valid redirect or post-logout redirect URIs.

**To Reproduce**
1. Configure a client with a wildcard redirect URI (for example, `https://example.com/*`)
2. Pass a URI that should satisfy that URI in an authentication request (for example, `https://example.com/test`)
3. See that the URI is not valid

**Expected behavior**
Wildcard URIs should be considered valid, as web applications should be able to have a variable entrypoint, for example if someone were to link to a page that is not the default, or a user is on a page that they want to return to after authenticating

**Desktop (please complete the following information):**
- OS: Debian 10
- Browser N/A

**Additional context**
The problem seems to be [here](https://github.com/zitadel/oidc/blob/main/pkg/op/auth_request.go#L294), for example.  When checking if a URI is valid, it does literal comparison but does not account for wildcards.  This is not the only place where this problem may occur though

**Comment by muir** [comment]
I'll take this one.

**Comment by fforootd** [comment]
Yes this makes sense to implement, we have the same requirement here https://github.com/zitadel/zitadel/discussions/3161

**Comment by muir** [comment]
> Yes this makes sense to implement, we have the same requirement here [zitadel/zitadel#3161](https://github.com/zitadel/zitadel/discussions/3161)

@fforootd I read those comments.   I know that @mitchwadair needs globs in production so forcing devMode=true isn't great (suggested in the above thread).

On the other hand, a real glob package, like https://pkg.go.dev/github.com/gobwas/glob#Compile will make `?` into a single-character wildcard and that could inadvertently loosen existing implementations.

I see two paths forward:

1. Change the interpretation of RedirectURIs to be globs and not worry about the possibility of a `?` or `*` in a URL.
2. Add a new RedirectURIGlobs() optional method (make it required in the `next` branch) to `client.Client` 

Whatever is done for `RedirectURIs()` should also be done for `PostLogoutRedirectURIs`

An option for the `next` branch would be to change the signature so that these methods return two slices instead of one.  I think that would be nicer but it's a breaking change that would add to the burden of switching to `next`.

cc @muhlemmer

**Comment by livio-a** [comment]
> > Yes this makes sense to implement, we have the same requirement here [zitadel/zitadel#3161](https://github.com/zitadel/zitadel/discussions/3161)
> 
> @fforootd I read those comments. I know that @mitchwadair needs globs in production so forcing devMode=true isn't great (suggested in the above thread).

Just for my understanding, @mitchwadair do you need wildcards in the path or also for domain names?
> Wildcard URIs should be considered valid, as web applications should be able to have a variable entrypoint, for example if someone were to link to a page that is not the default, or a user is on a page that they want to return to after authenticating

Because a dynamic path can be handled by the state parameter. We also do that in our single page app.

**Comment by mitchwadair** [comment]
> Just for my understanding, @mitchwadair do you need wildcards in the path or also for domain names?

I need them in the path, though `*` by itself should be valid as well (if you want to foot-gun yourself in production).

> Because a dynamic path can be handled by the state parameter. We also do that in our single page app.

This is true, but should not be the only solution IMO
