### ISSUE TITLE
feat: provide the IDToken to TerminateSession

### ISSUE THREAD

**Issue by muir** [zitadel/oidc#326]
**Is your feature request related to a problem? Please describe.**

For `TerminateSession` to know exactly which session it's terminating, it needs some way to find the session.  The current API provides `userIDString` and `clientIDString`.  That is not enough to uniquely identify a session.  Without uniquely identifying the session, too many sessions may be terminated.  Without Without uniquely identifying the session, if the server is a identity proxy, it may not be possible to terminate all upstream (proxied) sessions.

**Describe the solution you'd like**

Change the API of `TerminateSession` to include the value passed in the original request as `id_token_hint`.

**Describe alternatives you've considered**

#325 and extract the information myself.

**Comment by muhlemmer** [comment]
CC @livio-a, as we shortly discussed re-designing the session management yesterday and perhaps this can be taken up into the design.

**Comment by muir** [comment]
When the call to `TerminateSession` is due to an API call, `id_token_hint` probably should be provided.  However, it the call is due to a redirect, then `id_token_hint` will not be present.  In that situation, the call to `TerminateSession` could include a RequestID if a RequestID was set in a cookie earlier when providing the authentication code.

**Comment by muhlemmer** [comment]
We want to propose the following:

1. `op.EndSessionRequest`  to include a field with `Claims`.
2. Nn `op.EndSessionRequest` you can add other fields from the original `*oidc.EndSessionRequest` also, if needed for your usecase.
3. `ValidateEndSessionRequest` sets those fields where possible. For example, if `req.IdTokenHint` is not empty claims can be set to the `op.EndSessionRequest` in this branch:
https://github.com/zitadel/oidc/blob/a08ce5009112da5ee4c8db01dcd51a871c0b934e/pkg/op/session.go#L62-L71
4. Pass the complete  `op.EndSessionRequest` to `TerminateSession`, instead of `userID` and `clientID`. The implementation can obtain those from the request. (or any other data required)

```go
TerminateSession(ctx context.Context, req *EndSessionRequest) error
```

**Comment by muir** [comment]
@muhlemmer I could build according to your suggestion.  I could make it backwards compatible by introducing a new `TerminateSessionWithRequest` that includes the revised `EndSessionRequest`.  `TerminateSession` would be deprecated now and removed in `next`.

**Comment by muhlemmer** [comment]
This seems to be resolved by https://github.com/zitadel/oidc/pull/418
